spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          env:
          - name: SPRING_APPLICATION_NAME
            value: camel-boot
          - name: SPRING_CLOUD_KUBERNETES_ENABLED
            value: true
          - name: SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED
            value: true
